### ISSUE TITLE
关于 headers 

### ISSUE THREAD

**Issue by yifenglv46** [yanwii/pet-chain#3]
你好 headers  是 要 用  source 还是 parsed

**Comment by yifenglv46** [comment]
是不是 有 purchase 出现 就是 正常工作了？

**Comment by yanwii** [comment]
是的，这个我没说清楚。
________________________________
发件人: yifenglv46 <notifications@github.com>
发送时间: 2018年2月5日 10:32
收件人: yanwii/pet-chain
抄送: Subscribed
主题: Re: [yanwii/pet-chain] 关于 headers (#3)


是不是 有 purchase 出现 就是 正常工作了？

―

**Comment by yifenglv46** [comment]
没事 感谢 大佬分享 只是刷了一会 一只都没买成 可能竞争太厉害
{u'errorNo': u'10002', u'errorMsg': u'\u6709\u4eba\u62a2\u5148\u4e0b\u5355\u5566', u'data': None, u'timestamp': u'2018-02-05 18:38:17'}
[->] purchase
{u'errorNo': u'10002', u'errorMsg': u'\u6709\u4eba\u62a2\u5148\u4e0b\u5355\u5566', u'data': None, u'timestamp': u'2018-02-05 18:38:21'}
这个要去处理吗？

**Comment by yanwii** [comment]
是的，不知道多少人在怼着刷。
这个是购买失败了
________________________________
发件人: yifenglv46 <notifications@github.com>
发送时间: 2018年2月5日 10:40
收件人: yanwii/pet-chain
抄送: yanwii; Comment
主题: Re: [yanwii/pet-chain] 关于 headers (#3)


没事 感谢 大佬分享 只是刷了一会 一只都没买成 可能竞争太厉害
{u'errorNo': u'10002', u'errorMsg': u'\u6709\u4eba\u62a2\u5148\u4e0b\u5355\u5566', u'data': None, u'timestamp': u'2018-02-05 18:38:17'}
[->] purchase
{u'errorNo': u'10002', u'errorMsg': u'\u6709\u4eba\u62a2\u5148\u4e0b\u5355\u5566', u'data': None, u'timestamp': u'2018-02-05 18:38:21'}
这个要去处理吗？

―
