### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cuican008** [yanwii/pet-chain#4]
Traceback (most recent call last):
  File "pet_chain.py", line 153, in <module>
    if sys.argv[1] == "run":
IndexError: list index out of range

**Comment by yifenglv46** [comment]
一样的

**Comment by yanwii** [comment]
`python2 pet_chain.py run`

**Comment by yifenglv46** [comment]
奇怪 再也 没有 成功 过 我用的 另一台机

**Comment by yanwii** [comment]
现在炒得很凶
