### ISSUE TITLE
竞争压力太大 出1800 都刷不到狗

### ISSUE THREAD

**Issue by cuican008** [yanwii/pet-chain#5]
{{u'errorNo'u'errorNo': : u'05'u'05', , u'errorMsg'u'errorMsg': : u''u'', , u'timestamp'u'timestamp': : u'2018-02-05 22:05:07'u'2018-02-05 22:05:07'}}

[->] purchase
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp'{: u'errorNo'u'2018-02-05 22:05:08': }u'05'
, {u'errorMsg'u'errorNo': : u''u'05', , u'timestamp'u'errorMsg': : u'2018-02-05 22:05:08'u''{}, u'errorNo'
u'timestamp': : u'05'u'2018-02-05 22:05:08', }u'errorMsg'
: u'', u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp'{: u'errorNo'u'2018-02-05 22:05:08': }u'05'{
, u'errorNo'u'errorMsg': : u'05'u'', , u'errorMsg'u'timestamp': : u''u'2018-02-05 22:05:08', {}u'timestamp'u'errorNo'
: : u'05'u'2018-02-05 22:05:08', }u'errorMsg'
: u'', u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05'{, u'errorNo'u'errorMsg': : u''u'05', , u'timestamp'u'errorMsg': : u'2018-02-05 22:05:08'u''},
u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp': u'2018-02-05 22:05:08'}
{u'errorNo': u'05', u'errorMsg': u'', u'timestamp': u'2018-02-05 22:05:08'}
{{u'errorNo'u'errorNo': : u'05'u'05', , u'errorMsg'u'errorMsg': : u''u'', , u'timestamp'u'timestamp': : u'2018-02-05 22:05:08'u'2018-02-05 22:05:08'}}

{{u'errorNo'u'errorNo': : u'05'u'05', , u'errorMsg'u'errorMsg': : u''u'', , u'timestamp'u'timestamp': : u'2018-02-05 22:05:08'u'2018-02-05 22:05:08'}}

**Comment by cuican008** [comment]
没有反复进行 刷一次后就不刷了

**Comment by yanwii** [comment]
现在应该可以的，刚才程序有点问题
